### ISSUE TITLE
`yarn install` fails

### ISSUE THREAD

**Issue by tex0l** [JiriHoffmann/react-native-cryptopp#22]
When pulling the project on the latest main branch, and running `yarn install`:
```bash
react-native-cryptopp git:(main) yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native@0.68.0" has incorrect peer dependency "react@17.0.2".
warning "react-native > metro-react-native-babel-transformer@0.67.0" has unmet peer dependency "@babel/core@*".
warning "react-native > react-shallow-renderer@16.14.1" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
warning "react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
[4/4] 🔨  Building fresh packages...
$ bob build && husky install && yarn download_cryptopp
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 2 files in src with babel
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 2 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
test/e2e/tests/firstTest.spec.ts:1:43 - error TS2307: Cannot find module 'detox' or its corresponding type declarations.

1 import {expect, device, element, by} from 'detox';
                                            ~~~~~~~

test/e2e/testSetup.ts:1:29 - error TS2307: Cannot find module 'detox' or its corresponding type declarations.

1 import {cleanup, init} from 'detox';
                              ~~~~~~~

test/e2e/testSetup.ts:6:9 - error TS2339: Property 'getEnv' does not exist on type 'typeof jasmine'.

6 jasmine.getEnv().addReporter(adapter);
          ~~~~~~


Found 3 errors in 2 files.

Errors  Files
     1  test/e2e/tests/firstTest.spec.ts:1
     2  test/e2e/testSetup.ts:1
✖ Failed to build definition files.
bob build

build files for publishing

Options :
  --help     Affiche l'aide                                            [booléen]
  --version  Affiche le numéro de version                              [booléen]

Error: Failed to build definition files.
    at build (/Users/timothee/SealdProjects/react-native-cryptopp/node_modules/react-native-builder-bob/lib/targets/typescript.js:112:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.handler (/Users/timothee/SealdProjects/react-native-cryptopp/node_modules/react-native-builder-bob/lib/index.js:379:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by tex0l** [comment]
My bad, old repo..
