### ISSUE TITLE
Still can't run example project

### ISSUE THREAD

**Issue by roaringUnicorn** [JiriHoffmann/react-native-cryptopp#8]
I'm trying to run the example with @tex0l, but I ran into another error at build time.
It's a linking error of hmac headers. As you're working on it, maybe you can help on that ?

```
yarn install
cd example
yarn install
yarn run android
```

FYI, i'm running on ubuntu 22, building for android.
It now works fine for tex0l, but he's on a macbook. 

Full stacktrace:
```
example git:(main) ✗ yarn run android
yarn run v1.22.18
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 911 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Task :react-native-image-crop-picker:compileDebugJavaWithJavac

> Task :reactnativecryptopp:externalNativeBuildDebug FAILED
Build rncryptopp_armeabi-v7a
ninja: Entering directory `/home/clement/projects/react-native-cryptopp/android/.cxx/cmake/debug/armeabi-v7a'
/home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:317: error: undefined reference to 'rncryptopp::hmac::generate(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
/home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:326: error: undefined reference to 'rncryptopp::hmac::verify(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, bool*)'
/home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:334: error: undefined reference to 'rncryptopp::cmac::generate(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
/home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:343: error: undefined reference to 'rncryptopp::cmac::verify(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, bool*)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
73 actionable tasks: 7 executed, 66 up-to-date
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reactnativecryptopp:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/clement/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/clement/projects/react-native-cryptopp/android/.cxx/cmake/debug/armeabi-v7a rncryptopp}
  ninja: Entering directory `/home/clement/projects/react-native-cryptopp/android/.cxx/cmake/debug/armeabi-v7a'
  [1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/librncryptopp.so
  FAILED: ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/librncryptopp.so 
  : && /home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -O3 -frtti -fexceptions -Wall -fstack-protector-all -Wl -DONANDROID -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,librncryptopp.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/librncryptopp.so CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/aes-candidates.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/hash-functions.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/helpers.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/insecure.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/key-derivation.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/public-key.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/utils.cpp.o CMakeFiles/rncryptopp.dir/cpp-adapter.cpp.o  ../../../../../cpp/android/libcryptopp_armeabi-v7a.a ../../../../build/react-native-0.67.1.aar/jni/armeabi-v7a/libreactnativejni.so ../../../../build/react-native-0.67.1.aar/jni/armeabi-v7a/libjsi.so /home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/21/liblog.so -landroid -latomic -lm && :
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:317: error: undefined reference to 'rncryptopp::hmac::generate(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:326: error: undefined reference to 'rncryptopp::hmac::verify(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, bool*)'
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:334: error: undefined reference to 'rncryptopp::cmac::generate(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:343: error: undefined reference to 'rncryptopp::cmac::verify(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, bool*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reactnativecryptopp:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/clement/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/clement/projects/react-native-cryptopp/android/.cxx/cmake/debug/armeabi-v7a rncryptopp}
  ninja: Entering directory `/home/clement/projects/react-native-cryptopp/android/.cxx/cmake/debug/armeabi-v7a'
  [1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/librncryptopp.so
  FAILED: ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/librncryptopp.so 
  : && /home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -O3 -frtti -fexceptions -Wall -fstack-protector-all -Wl -DONANDROID -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,librncryptopp.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/librncryptopp.so CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/aes-candidates.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/hash-functions.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/helpers.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/insecure.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/key-derivation.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/public-key.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp.o CMakeFiles/rncryptopp.dir/home/clement/projects/react-native-cryptopp/cpp/utils.cpp.o CMakeFiles/rncryptopp.dir/cpp-adapter.cpp.o  ../../../../../cpp/android/libcryptopp_armeabi-v7a.a ../../../../build/react-native-0.67.1.aar/jni/armeabi-v7a/libreactnativejni.so ../../../../build/react-native-0.67.1.aar/jni/armeabi-v7a/libjsi.so /home/clement/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/21/liblog.so -landroid -latomic -lm && :
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:317: error: undefined reference to 'rncryptopp::hmac::generate(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:326: error: undefined reference to 'rncryptopp::hmac::verify(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, bool*)'
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:334: error: undefined reference to 'rncryptopp::cmac::generate(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
  /home/clement/projects/react-native-cryptopp/cpp/react-native-cryptopp.cpp:343: error: undefined reference to 'rncryptopp::cmac::verify(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned int, bool*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (/home/clement/projects/react-native-cryptopp/example/node_modules/execa/index.js:174:9)
    at /home/clement/projects/react-native-cryptopp/example/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/home/clement/projects/react-native-cryptopp/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/clement/projects/react-native-cryptopp/example/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tex0l** [comment]
I can confirm that on macOS 12.3.1 it works, and we compared with @roaringUnicorn the way we tested it, it's strictly identical.

**Comment by JiriHoffmann** [comment]
I think I ran into the same issue, deleting the android/app/build/.cxx folder fixed it, for some reason it doesn't update the cache

**Comment by roaringUnicorn** [comment]
Thanks, it was that. I can run the example now.
